build:
  correctness:
    build:
      image: vaticle-ubuntu-22.04
      type: foreground
      command: |
        bazel build //...
    sync-dependencies:
      image: vaticle-ubuntu-22.04
      filter:
        owner: vaticle
        branch: [master, development]
      dependencies: [build]
      command: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @vaticle_dependencies//tool/sync:dependencies -- --source ${FACTORY_REPO}@${FACTORY_COMMIT}
  execution:
    - build
